mode: offline
project: cifar10-vae
name: vae-training
device: cuda:1
model_type: gan
data_root: ./data

gan:
  seed: 42
  data_root: ${data_root} 
  device: ${device}
  batch_size: 128
  num_workers: 4
  n_steps: 50001
  latent_dim: 512
  
  glr: 1e-5
  gbetas: [0.5, 0.999]
  gdecay: 1e-5
  
  dlr: 1e-2
  dbetas: [0.5, 0.999]
  ddecay: 1e-5

  log_freq: 100
  image_freq: 1000
  save_freq: 1000

vae:
  data_root: ${data_root} 
  device: ${device}
  batch_size: 512
  num_workers: 8
  n_epochs: 100
  learning_rate: 1e-3
  weight_decay: 1e-5
  lr_decay: 0.999
  latent_dim: 256
  beta: 0.5

cls:
  data_root: ${data_root} 
  device: ${device}
  batch_size: 512
  num_workers: 4
  n_epochs: 100
  learning_rate: 1e-3
  weight_decay: 1e-5

hydra:
  run:
    dir: "."