name: d2d
device: cuda:0
save_checkpoint_freq: 5
log_fwd_freq: 1
log_bwd_freq: 1

# training
batch_size: 128
val_batch_size: 10000
backward_first: true
fwd_optim_lr: 8e-4
bwd_optim_lr: 8e-4
num_sb_steps: 20
num_fwd_steps: 4000
num_bwd_steps: 4000
fwd_ema_decay: 0.0
bwd_ema_decay: 0.0
matching_method: ll
train_log_var: true

# ref process
alpha: 0.0
dt: 0.01
t_max: 0.2
n_steps: 20