name: d2e
device: cuda

# training parameters:
backward_first: true
fwd_optim_lr: 8e-4
bwd_optim_lr: 8e-4
save_checkpoint_freq: 5

threshold: 5e-6
n_sb_iter: 10000
num_fwd_steps: 1
num_bwd_steps: 1
log_fwd_freq: 100
log_bwd_freq: 100

# process parameters:
alpha: 4.0
dt: 0.0006
t_max: 0.0012
n_steps: 20

batch_size: 512
drift_reg_coeff: 0.01

n_trajectories: 2
drift_reg_coeff: 0.0
reuse_backward_trajectory: false

buffer_type: simple
buffer_size: 1024
langevin_step_size: 0.001
num_langevin_update_steps: 50