# process parameters:
alpha: 4.0
gamma: 0.0006
t_max: 0.0012
n_sampling_steps: 20

# sb parameters
num_sb_steps: 20
threshold: 5e-6
max_num_iters_per_step: 6000

# learning parameters
batch_size: 256
lr_forward: 8e-4
lr_backward: 8e-4
save_checkpoint_freq: 5