name: d2e
device: cpu

# training parameters:
backward_first: true
fwd_optim_lr: 8e-4
bwd_optim_lr: 8e-4
save_checkpoint_freq: 5

threshold: 5e-6
n_sb_iter: 5
num_fwd_steps: 6000
num_bwd_steps: 6000

# process parameters:
alpha: 4.0
dt: 0.0006
t_max: 0.0012
n_steps: 20

batch_size: 512

reuse_backward_trajectory:  true
buffer_type: langevin
buffer_size: 1024
langevin_step_size: 0.001
num_langevin_update_steps: 10