defaults:
  - _self_
  - sampler: d2d_sb

exp:
  name: sb-experiment
  project: sb
  mode: online

data:
  p_0: 
    name: swiss_roll
    args: 
      shift: null
      noise: 0.1
  p_1:
    name: mix_of_gaussians
    args: 
      means: [[-0.7, 0.7],[-0.7, -0.7],[0.7, 0.7],[0.7, -0.7]]
      sigmas: [[0.1, 0.1],[0.1, 0.1],[0.1, 0.1],[0.1, 0.1]]

models:
  fwd:
    t_emb_size: 64
    x_emb_size: 64
    n_main_body_layers: 3
    predict_log_var: true
  bwd:
    t_emb_size: 64
    x_emb_size: 64
    n_main_body_layers: 3
    predict_log_var: true