defaults:
  - _self_
  - /data@data.p_0: cross
  - /data@data.p_1: gmm
  - /models@models.fwd: d64-tv
  - /models@models.bwd: d64-tv
  - sampler: e2e
  - buffer: decoupled_langevin_2d

exp:
  id: null
  resume: allow
  name: sb-e2e
  project: sb-e2e-ablations
  mode: online

hydra:
  run:
    dir: "."
  output_subdir: null
  job_logging:
    disable_existing_loggers: true
  verbose: false