sampler:
  name: d2e
  device: cuda:0

  # training parameters:
  backward_first: true
  fwd_optim_lr: 8e-4
  bwd_optim_lr: 8e-4
  save_checkpoint_freq: 5

  threshold: 5e-6
  n_sb_iter: 20
  num_fwd_steps: 5000
  num_bwd_steps: 5000
  log_fwd_freq: 1
  log_bwd_freq: 1

  alpha: 0.0
  dt: 0.004
  t_max: 0.08
  n_steps: 20

  batch_size: 64
  val_batch_size: 128

  n_trajectories: 2
  drift_reg_coeff: 0.0
  reuse_backward_trajectory: false

  policy: mixed
  off_policy_fraction: 0.25
  start_mixed_from: 0
  buffer_type: simple
  buffer_size: 1024
  langevin_step_size: 0.001
  num_langevin_update_steps: 50

exp:
  id: null
  resume: allow
  name: outsourced-sb-mnist
  project: sb
  mode: online

data:
  p_0: 
    name: simple_gaussian
    args: 
      mean: 0.0
      std: 1.0
      dim: 50
      device: ${sampler.device}
  p_1:
    name: cls_reward_dist
    args: 
      generator_type: cifar-gan-z50
      classifier_type: cifar_cls
      prior_dim: 50
      target_classes: [5]
      reward_type: sum
      device: ${sampler.device}

models:
  fwd:
    t_emb_size: 64
    x_emb_size: 64
    in_dim: 50
    out_dim: 50
    n_main_body_layers: 5
    predict_log_var: true
    use_residual: false
  bwd:
    t_emb_size: 64
    x_emb_size: 64
    in_dim: 50
    out_dim: 50
    n_main_body_layers: 5
    predict_log_var: true
    use_residual: false

hydra:
  run:
    dir: "."
  output_subdir: null
  job_logging:
    disable_existing_loggers: true
  verbose: false