sampler:
  name: d2e
  device: cuda:0

  # logging
  save_checkpoint_freq: 5
  log_fwd_freq: 1
  log_bwd_freq: 1
  
  # training
  batch_size: 512
  matching_method: ll
  backward_first: true
  num_sb_steps: 100
  fwd_optim_lr: 5e-4
  bwd_optim_lr: 5e-4
  num_fwd_steps: 2000
  num_bwd_steps: 100
  fwd_ema_decay: 0.0
  bwd_ema_decay: 0.0

  # ref process
  dt: 0.04
  alpha: 0.0
  t_max: 0.8
  n_steps: 20

  # policy
  n_trajectories: 2
  start_mixed_from: 0
  off_policy_fraction: 0.4
  
  # bufferx
  buffer_type: langevin
  buffer_size: 2048
  buffer_sampler: ula2
  init_step_size: 0.5
  anneal_value: 0.1
  num_langevin_steps: 10
  noise_start_ratio: 0.5
  reward_proportional_sample: true
  hmc_freq: 4

exp:
  id: null
  resume: allow
  name: outsourced-sb
  project: sb
  mode: online

data:
  p_0: 
    name: simple_gaussian
    args: 
      mean: 0.0
      std: 1.0
      dim: 256
      device: ${sampler.device}
  p_1:
    name: cls_reward_dist
    args: 
      generator_type: cifar10-gan-z256
      classifier_type: cifar10-cls
      prior_dim: 256
      target_classes: [5]
      reward_type: sum
      device: ${sampler.device}

models:
  fwd:
    t_emb_size: 128
    x_emb_size: 256
    in_dim: 256
    out_dim: 256
    n_main_body_layers: 6
    predict_log_var: true
    use_residual: false
  bwd:
    t_emb_size: 128
    x_emb_size: 256
    in_dim: 256
    out_dim: 256
    n_main_body_layers: 6
    predict_log_var: true
    use_residual: false

hydra:
  run:
    dir: "."
  output_subdir: null
  job_logging:
    disable_existing_loggers: true
  verbose: false