sampler:
  name: d2e
  device: cuda:0
  save_checkpoint_freq: 5
  log_fwd_freq: 1
  log_bwd_freq: 1
  
  # training
  n_sb_iter: 100
  batch_size: 64
  backward_first: true
  fwd_optim_lr: 8e-4
  bwd_optim_lr: 8e-4
  num_fwd_steps: 2000
  num_bwd_steps: 500
  fwd_ema_decay: 0.0
  bwd_ema_decay: 0.0
  matching_method: ll

  # ref process
  alpha: 0.0
  dt: 0.04
  t_max: 0.d8
  n_steps: 20

  # policy
  n_trajectories: 2
  start_mixed_from: 0
  off_policy_fraction: 0.7
  reuse_backward_trajectory: false
  
  # buffer
  buffer_type: langevin
  buffer_size: 128
  langevin_step_size: 0.1
  num_langevin_update_steps: 10

exp:
  id: null
  resume: allow
  name: outsourced-sb-mnist
  project: sb
  mode: online

data:
  p_0: 
    name: simple_gaussian
    args: 
      mean: 0.0
      std: 1.0
      dim: 50
      device: ${sampler.device}
  p_1:
    name: cls_reward_dist
    args: 
      generator_type: cifar10-gan-z50
      classifier_type: cifar10-cls
      prior_dim: 50
      target_classes: [5]
      reward_type: sum
      device: ${sampler.device}

models:
  fwd:
    t_emb_size: 64
    x_emb_size: 64
    in_dim: 50
    out_dim: 50
    n_main_body_layers: 4
    predict_log_var: true
    use_residual: false
  bwd:
    t_emb_size: 64
    x_emb_size: 64
    in_dim: 50
    out_dim: 50
    n_main_body_layers: 4
    predict_log_var: true
    use_residual: false

hydra:
  run:
    dir: "."
  output_subdir: null
  job_logging:
    disable_existing_loggers: true
  verbose: false