defaults:
  - _self_
  - /data@data.p_0: d256normal
  - /data@data.p_1: cifar10-gan-d256
  - /models@models.fwd: d256
  - /models@models.bwd: d256
  - sampler: d2e-cifar10

exp:
  id: null
  resume: allow
  name: outscourced
  project: sb
  mode: online

hydra:
  run:
    dir: "."
  output_subdir: null
  job_logging:
    disable_existing_loggers: true
  verbose: false