defaults:
  - _self_
  - /data@data.p_0: d512normal
  - /data@data.p_1: cifar10-sg
  - /models@models.fwd: d512
  - /models@models.bwd: d512
  - sampler: d2e-sg
  - buffer: decoupled_langevin

exp:
  id: null
  resume: allow
  name: outscourced
  project: sb
  mode: online

hydra:
  run:
    dir: "."
  output_subdir: null
  job_logging:
    disable_existing_loggers: true
  verbose: false